name: crypto-gold

on:
  schedule:
    - cron: "*/5 * * * *"   # 5 percenként (UTC)
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -V
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate feeds (SOL + GOLD_CFD)
        env:
          TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
          TD_PAUSE: "2.0"
          ASSET_ONLY: "SOL,GOLD_CFD"
          TD_M5_MIN_AGE: "900"      # 5m OHLC csak 15 perc után frissül
          TD_H1_MIN_AGE: "3600"     # 1h OHLC csak 1 óra után frissül
          TD_H4_MIN_AGE: "14400"    # 4h OHLC csak 4 óra után frissül
          DEBUG: "1"
        run: python Trading.py

      # >>> ÚJ: az NSDQ100 (QQQ) meglévő Pages-tartalom megőrzése
      - name: Merge existing Pages content (preserve NSDQ100)
        run: |
          set -e
          BASE="https://wildfire0007.github.io/market-feed"
          mkdir -p public/NSDQ100 public/SOL public/GOLD_CFD
          for A in NSDQ100; do
            for F in spot.json klines_5m.json klines_1h.json klines_4h.json signal.json; do
              URL="$BASE/$A/$F"
              curl -fsS -o "public/$A/$F" "$URL" && echo "Preserved $A/$F" || true
            done
            # PNG chart (ha van)
            curl -fsS -o "public/$A/chart_1d.png" "$BASE/$A/chart_1d.png" || true
          done
      # <<<

      - name: Ensure index.html
        run: |
          mkdir -p public
          printf '%s\n' \
            '<!doctype html><meta charset="utf-8"><title>market-feed</title>' \
            '<h1>market-feed</h1><ul>' \
            '<li><a href="./SOL/signal.json">SOL/signal.json</a></li>' \
            '<li><a href="./NSDQ100/signal.json">NSDQ100/signal.json</a></li>' \
            '<li><a href="./GOLD_CFD/signal.json">GOLD_CFD/signal.json</a></li>' \
            '<li><a href="./analysis.html">analysis.html</a></li>' \
            '</ul>' > public/index.html

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
