name: Generate feeds (RAW-ready, 1M trigger)

on:
  schedule:
    - cron: "*/30 5-21 * * *"   # UTC; kb. 07:00–23:59 Budapest
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Export Twelve Data key (ha van)
        if: ${{ secrets.TWELVEDATA_API_KEY != '' }}
        run: echo "TWELVEDATA_API_KEY=${{ secrets.TWELVEDATA_API_KEY }}" >> $GITHUB_ENV

      - name: Run feed generator
        run: python Trading.py

      - name: Commit JSON outputs
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add all_SOL.json all_NSDQ100.json all_GOLD_CFD.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update all_*.json (auto)"
            git push
          fi
