name: Build & Deploy market feed

# --- Mikor fusson ---
on:
  # 1) 5 percenként (UTC szerint)
  schedule:
    - cron: "*/5 * * * *"
  # 2) Azonnal, ha a public/ vagy a kód változik (push a main-re)
  push:
    branches: [ main ]
    paths:
      - 'public/**'
      - 'Trading.py'
      - 'requirements.txt'
  # 3) Kézi indítás az Actions felületről
  workflow_dispatch:

# --- Ne fusson párhuzamosan; mindig a legutóbbit tartsuk meg ---
concurrency:
  group: market-feed
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11 (pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script (writes to public/)
        run: |
          python Trading.py

      - name: Upload Pages artifact (public/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
