name: build-and-deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "*/30 6-20 * * 1-5"  # hétköznap 06:00–20:59 között 30 percenként (UTC)

permissions:
  contents: read
  pages: write
  id-token: write

# NE állítsuk le a futó buildet új push esetén
concurrency:
  group: "pages-deploy"
  cancel-in-progress: false

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -V
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Wipe public (force clean)
        run: |
          rm -rf public
          mkdir -p public

      - name: Generate feed (safe)
        env:
          TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
        run: |
          python Trading.py

      # opcionális: gyors ellenőrzés, hogy létrejöttek-e a fájlok
      - name: Inspect output
        run: |
          ls -la public || true
          test -f public/index.html
          test -f public/status.json

      - name: Upload artifact (Pages)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
