name: Build & Publish (Pages)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 6-20 * * 1-5" # hétköznap 06:00–20:59 (UTC) 30 percenként

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-deploy"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -V
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 1) Generálás
      - name: Generate feeds (Trading.py)
        env:
          TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
        run: |
          python Trading.py

      - name: Generate analysis (Analysis.py)
        run: |
          if [ -f Analysis.py ]; then python Analysis.py; fi

      # 2) Kimenetek összegyűjtése a public/ alá
      - name: Collect outputs into public/
        run: |
          set -e
          rm -rf public
          mkdir -p public

          # status / összefoglalók (ha vannak)
          if [ -f status.json ]; then cp status.json public/status.json; fi
          if [ -f analysis.html ]; then cp analysis.html public/analysis.html; fi
          if [ -f analysis_summary.json ]; then cp analysis_summary.json public/analysis_summary.json; fi

          # eszközök
          ASSETS="SOL NSDQ100 GOLD_CFD"
          for a in $ASSETS; do
            mkdir -p "public/$a"
            for f in spot.json klines_5m.json klines_1h.json klines_4h.json signal.json decision.json chart_1d.png; do
              if [ -f "$a/$f" ]; then
                cp "$a/$f" "public/$a/$f"
              fi
            done
          done

          # index.html – gyorskijárat
          cat > public/index.html <<'HTML'
          <!doctype html><meta charset="utf-8"><title>market-feed</title>
          <h1>market-feed</h1>
          <ul>
            <li><a href="./status.json">status.json</a></li>
            <li><a href="./analysis.html">analysis.html</a></li>
            <li><a href="./analysis_summary.json">analysis_summary.json</a></li>
          </ul>
          <h2>SOL</h2>
          <ul>
            <li><a href="./SOL/spot.json">SOL/spot.json</a></li>
            <li><a href="./SOL/klines_5m.json">SOL/klines_5m.json</a></li>
            <li><a href="./SOL/klines_1h.json">SOL/klines_1h.json</a></li>
            <li><a href="./SOL/klines_4h.json">SOL/klines_4h.json</a></li>
            <li><a href="./SOL/signal.json">SOL/signal.json</a></li>
            <li><a href="./SOL/decision.json">SOL/decision.json</a></li>
            <li><a href="./SOL/chart_1d.png">SOL/chart_1d.png</a></li>
          </ul>
          <h2>NSDQ100</h2>
          <ul>
            <li><a href="./NSDQ100/spot.json">NSDQ100/spot.json</a></li>
            <li><a href="./NSDQ100/klines_5m.json">NSDQ100/klines_5m.json</a></li>
            <li><a href="./NSDQ100/klines_1h.json">NSDQ100/klines_1h.json</a></li>
            <li><a href="./NSDQ100/klines_4h.json">NSDQ100/klines_4h.json</a></li>
            <li><a href="./NSDQ100/signal.json">NSDQ100/signal.json</a></li>
            <li><a href="./NSDQ100/decision.json">NSDQ100/decision.json</a></li>
          </ul>
          <h2>GOLD_CFD</h2>
          <ul>
            <li><a href="./GOLD_CFD/spot.json">GOLD_CFD/spot.json</a></li>
            <li><a href="./GOLD_CFD/klines_5m.json">GOLD_CFD/klines_5m.json</a></li>
            <li><a href="./GOLD_CFD/klines_1h.json">GOLD_CFD/klines_1h.json</a></li>
            <li><a href="./GOLD_CFD/klines_4h.json">GOLD_CFD/klines_4h.json</a></li>
            <li><a href="./GOLD_CFD/signal.json">GOLD_CFD/signal.json</a></li>
            <li><a href="./GOLD_CFD/decision.json">GOLD_CFD/decision.json</a></li>
          </ul>
          HTML

      # 3) Kötelező fájlok ellenőrzése – ha hiányzik, hibázzon a build
      - name: Validate required files
        run: |
          set -e
          test -f public/index.html
          # legalább a SOL készlet legyen jelen
          test -f public/SOL/spot.json
          test -f public/SOL/klines_1h.json
          test -f public/SOL/klines_4h.json

      # 4) Debug listázás
      - name: List public (debug)
        run: |
          echo "==== public ===="
          find public -type f -maxdepth 3 | sort

      # 5) Feltöltés Pages-re
      - name: Upload artifact (Pages)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
