name: Build & Publish (GitHub Pages)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 6-20 * * 1-5"  # hétköznap 06:00–20:59 (UTC) 30 percenként

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-deploy"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Prepare public dir
        run: |
          mkdir -p public

      - name: Install dependencies
        run: |
          python -V
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate feeds (Trading.py)
        env:
          TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
        run: |
          python Trading.py
          echo "[KÉSZ] Fejlécek/decisions legenerálva."

      - name: Run Analysis (optional)
        continue-on-error: true
        run: |
          if [ -f Analysis.py ]; then python Analysis.py; elif [ -f analysis.py ]; then python analysis.py; else echo "Analysis script nem található, tovább lépek."; fi

      - name: Ensure index.html
        run: |
          # Egyszerű index oldal a gyökérbe
          printf '%s\n' \
            '<!doctype html><meta charset="utf-8"><title>market-feed</title>' \
            '<h1>market-feed</h1>' \
            '<ul>' \
            '<li><a href="./SOL/signal.json">SOL/signal.json</a></li>' \
            '<li><a href="./NSDQ100/signal.json">NSDQ100/signal.json</a></li>' \
            '<li><a href="./GOLD_CFD/signal.json">GOLD_CFD/signal.json</a></li>' \
            '<li><a href="./analysis.html">analysis.html</a></li>' \
            '</ul>' \
            > public/index.html

      - name: List public (debug)
        run: |
          echo "==== public (recursive) ===="
          find public -type f | sort || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
