name: Build & Publish (Pages)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 6-20 * * 1-5"   # hétköznap 06:00–20:59 (UTC) 30 percenként

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-deploy"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -V
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Show repo (pre-run)
        run: |
          echo "==== repo root (pre) ===="
          ls -la
          echo "==== python files ===="
          ls -la *.py || true

      # 1) Trading.py – hibánál se álljon le a job
      - name: Generate feeds (Trading.py)
        id: trading
        env:
          TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
        run: python Trading.py
        continue-on-error: true

      # 2) Fallback tiszta Bash-ban, ha Trading.py nem sikerült
      - name: Fallback placeholders (if Trading failed)
        if: steps.trading.outcome != 'success'
        run: |
          echo "::warning::Trading.py failed. Creating placeholder JSONs so Pages does not 404."
          set -e
          ASSETS="SOL NSDQ100 GOLD_CFD"
          FILES="spot.json klines_5m.json klines_1h.json klines_4h.json signal.json decision.json"
          for a in $ASSETS; do
            mkdir -p "$a"
            for f in $FILES; do
              p="$a/$f"
              if [ ! -f "$p" ]; then
                printf '{"ok": false, "error": "generator failed", "file": "%s"}\n' "$p" > "$p"
              fi
            done
          done
          echo "Placeholders created."

      # (opcionális) Analysis.py – ha van, fusson (de ne álljon meg hiba esetén)
      - name: Generate analysis (Analysis.py) — optional
        run: |
          if [ -f Analysis.py ]; then python Analysis.py || echo "::warning::Analysis.py failed (continuing)"; fi

      - name: Show repo (post-run)
        run: |
          echo "==== repo root (post) ===="
          ls -la
          for a in SOL NSDQ100 GOLD_CFD; do
            echo "---- $a ----"
            ls -la "$a" || true
          done

      - name: Collect outputs into public/
        run: |
          set -e
          rm -rf public
          mkdir -p public

          # top-level
          [ -f status.json ] && cp status.json public/status.json
          [ -f analysis.html ] && cp analysis.html public/analysis.html
          [ -f analysis_summary.json ] && cp analysis_summary.json public/analysis_summary.json

          ASSETS="SOL NSDQ100 GOLD_CFD"
          for a in $ASSETS; do
            mkdir -p "public/$a"
            for f in spot.json klines_5m.json klines_1h.json klines_4h.json signal.json decision.json chart_1d.png; do
              if [ -f "$a/$f" ]; then
                cp "$a/$f" "public/$a/$f"
              fi
            done
          done

          # minimál index.html – itt nyugodtan használunk heredocot, mert az HTML-t nem zavarja a behúzás
          cat > public/index.html <<'HTML'
          <!doctype html><meta charset="utf-8"><title>market-feed</title>
          <h1>market-feed</h1>
          <ul>
            <li><a href="./status.json">status.json</a></li>
            <li><a href="./analysis.html">analysis.html</a></li>
            <li><a href="./analysis_summary.json">analysis_summary.json</a></li>
          </ul>
          <h2>SOL</h2>
          <ul>
            <li><a href="./SOL/spot.json">SOL/spot.json</a></li>
            <li><a href="./SOL/klines_5m.json">SOL/klines_5m.json</a></li>
            <li><a href="./SOL/klines_1h.json">SOL/klines_1h.json</a></li>
            <li><a href="./SOL/klines_4h.json">SOL/klines_4h.json</a></li>
            <li><a href="./SOL/signal.json">SOL/signal.json</a></li>
            <li><a href="./SOL/decision.json">SOL/decision.json</a></li>
            <li><a href="./SOL/chart_1d.png">SOL/chart_1d.png</a></li>
          </ul>
          <h2>NSDQ100</h2>
          <ul>
            <li><a href="./NSDQ100/spot.json">NSDQ100/spot.json</a></li>
            <li><a href="./NSDQ100/klines_5m.json">NSDQ100/klines_5m.json</a></li>
            <li><a href="./NSDQ100/klines_1h.json">NSDQ100/klines_1h.json</a></li>
            <li><a href="./NSDQ100/klines_4h.json">NSDQ100/klines_4h.json</a></li>
            <li><a href="./NSDQ100/signal.json">NSDQ100/signal.json</a></li>
            <li><a href="./NSDQ100/decision.json">NSDQ100/decision.json</a></li>
          </ul>
          <h2>GOLD_CFD</h2>
          <ul>
            <li><a href="./GOLD_CFD/spot.json">GOLD_CFD/spot.json</a></li>
            <li><a href="./GOLD_CFD/klines_5m.json">GOLD_CFD/klines_5m.json</a></li>
            <li><a href="./GOLD_CFD/klines_1h.json">GOLD_CFD/klines_1h.json</a></li>
            <li><a href="./GOLD_CFD/klines_4h.json">GOLD_CFD/klines_4h.json</a></li>
            <li><a href="./GOLD_CFD/signal.json">GOLD_CFD/signal.json</a></li>
            <li><a href="./GOLD_CFD/decision.json">GOLD_CFD/decision.json</a></li>
          </ul>
          HTML

      - name: List public (debug)
        run: |
          echo "==== public ===="
          find public -type f -maxdepth 3 | sort

      - name: Upload artifact (Pages)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
