name: QQQ (US market hours) – Build & Publish

on:
  workflow_dispatch:
  schedule:
    # H-P 06–20 UTC, 15 percenként (QQQ miatt elég)
    - cron: "*/15 6-20 * * 1-5"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-deploy"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Prepare public dir
        run: mkdir -p public

      - name: Install dependencies
        run: |
          python -V
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate feeds (Trading.py)
        env:
          TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
        run: |
          python Trading.py
          echo "[OK] Trading.py lefutott."

      # --- Analysis oldal létrehozása, hogy ne legyen 404 ---
      - name: Publish analysis outputs (make analysis.html)
        run: |
          mkdir -p public
          if [ -f analysis_summary.json ]; then cp analysis_summary.json public/analysis_summary.json; fi
          cat > public/analysis.html <<'HTML'
          <!doctype html><meta charset="utf-8">
          <title>Analysis</title>
          <h1>Analysis summary</h1>
          <p><a href="./">← back</a></p>
          <pre id="out">Loading…</pre>
          <script>
            fetch('./analysis_summary.json')
              .then(r=>r.json())
              .then(j=>{ out.textContent = JSON.stringify(j, null, 2); })
              .catch(()=>{ out.textContent = 'No analysis_summary.json yet.'; });
          </script>
          HTML

      - name: Ensure index.html
        run: |
          cat > public/index.html <<'HTML'
          <!doctype html><meta charset="utf-8">
          <title>market-feed</title>
          <h1>market-feed</h1>
          <ul>
            <li><a href="./SOL/signal.json">SOL/signal.json</a></li>
            <li><a href="./NSDQ100/signal.json">NSDQ100/signal.json</a></li>
            <li><a href="./GOLD_CFD/signal.json">GOLD_CFD/signal.json</a></li>
            <li><a href="./analysis.html">analysis.html</a></li>
          </ul>
          HTML

      - name: List public (debug)
        run: find public -type f | sort || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
